### ISSUE TITLE
Ability to emit kebab-case instead of snakeCase

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/kube2pulumi#102]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, kube2pulumi emits snakeCase. Investigate the ability to emit kebab-case instead.

**Comment by phillipedwards** [comment]
:) valid question. I'm working on additional details, just wanted to get this as a placeholder.

**Comment by mjeffryes** [comment]
any further details @phillipedwards?

**Comment by rquitales** [comment]
Development for converting Kubernetes manifests to Pulumi programs has moved over to: https://github.com/pulumi/pulumi-converter-kubernetes.

This enhancement request for the new converter plugin can be tracked via: https://github.com/pulumi/pulumi-converter-kubernetes/issues/8
