### ISSUE TITLE
Failed on pystol ClusterServiceVersion

### ISSUE THREAD

**Issue by albert-zhong** [pulumi/kube2pulumi#49]
Got this error:
```
[31mError[0m: Invalid block definition

  on pcl-764300749.pp line 0:
   1: resource pystolPystol[1;4m.[0mv0.8.17ClusterServiceVersion "kubernetes:operators.coreos.com/v1alpha1:ClusterServiceVersion" {

Either a quoted string block label or an opening brace ("{") is expected here.

```
When I tried using the kube2pulumi web app on this [ClusterServiceVersion](https://github.com/operator-framework/community-operators/blob/master/community-operators/pystol/0.8.17/pystol.v0.8.17.clusterserviceversion.yaml)

**Comment by rquitales** [comment]
This is due to the object name containing periods, eg. `pystol.v0.8.17` when converting the intermediary PCL to target language. We'll need to normalize the name to prevent this.

**Comment by rquitales** [comment]
Development for converting Kubernetes manifests to Pulumi programs has moved over to: https://github.com/pulumi/pulumi-converter-kubernetes.

This bug has been addressed in the Kubernetes converter plugin.
