### ISSUE TITLE
Better Handling of CRDs

### ISSUE THREAD

**Issue by rawkode** [pulumi/kube2pulumi#53]
Currently, `kube2pulumi` bails when it encounters a CRD.

Instead, it should print a warning and continue through the file

I'm using `kube2pulumi` with the following code:

```shell
curl -fSsL -o infrastructure-components.yaml https://github.com/kubernetes-sigs/cluster-api-provider-packet/releases/download/v$(CLUSTER_API_PACKET_PROVIDER_VERSION)/infrastructure-components.yaml
./kube2pulumi typescript --file infrastructure-components.yaml
```

**Comment by EronWright** [comment]
Related to this, the `crd2pulumi` tool doesn't install `CustomResourceDefinition` resources ([as of 1.0.5](https://github.com/pulumi/crd2pulumi/issues/36)); it simply generates Pulumi code for using CRDs.

**Comment by rawkode** [comment]
Why is this marked as won't fix?
