### ISSUE TITLE
Generate error

### ISSUE THREAD

**Issue by krewi1** [pulumi/kube2pulumi#64]
When following README instructions, there is and error on generating pulumi resource:
> Error: binding types: type kubernetes:core/v1:ServiceSpecType must be an object, not a string

## Expected behavior
There is no error and resource is generated

## Context (Environment)
Using pulumi docker with installed kube2pulumi tool

**Comment by viveklak** [comment]
@krewi1 thanks for the report. Could you provide the spec snippet that you saw this on?

**Comment by krewi1** [comment]
Oh, it was my fold.. i was using v0.0.5 of kube2pulumi. I am sorry for that.
