### ISSUE TITLE
Suggestion: "component" mode

### ISSUE THREAD

**Issue by EronWright** [pulumi/kube2pulumi#70]
My application is composed of numerous Kubernetes manifests, each of which may be understood as a component of the application.  For example, I have `certmanager.yaml` and `webapp.yaml`.  I'd like to generate a `pulumi.ComponentResource` for each of the components, that I can assemble into a whole application using `index.ts`.

## Affected feature
Please enhance the generator with a `component` mode, which wraps the generated statements in a `pulumi.ComponentResource`.   Some specific suggestions:
1. Declare each sub-resource as a field of the component resource.
2. Generate an `Args` interface for the component resource.

For example, here's a hypothetical snippet of generated code for [cert-manager.yaml](https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml).

```ts
export class CertManager extends pulumi.ComponentResource {
    private readonly certManagerNamespace: kubernetes.core.v1.Namespace;
    private readonly cainjectorServiceAccount: kubernetes.core.v1.ServiceAccount;
    private readonly managerServiceAccount: kubernetes.core.v1.ServiceAccount;
    // ...

    constructor(name: string, args: CertManagerArgs, opts?: pulumi.ComponentResourceOptions) {
        super("CertManager", name, {}, opts);

        this.certManagerNamespace = new kubernetes.core.v1.Namespace("cert_managerNamespace", {
            apiVersion: "v1",
            kind: "Namespace",
            metadata: {
                name: "cert-manager",
            },
        }, { parent: this });

        // ...
    }
}

export interface CertManagerArgs {
}
```

**Comment by rquitales** [comment]
Development for converting Kubernetes manifests to Pulumi programs has moved over to: https://github.com/pulumi/pulumi-converter-kubernetes.

This enhancement has been addressed in the Kubernetes converter plugin.
