### ISSUE TITLE
`kube2pulumi` overwrites `index.ts` without any warning.

### ISSUE THREAD

**Issue by aureq** [pulumi/kube2pulumi#75]
When running `kube2pulumi`, it automatically outputs anything into `index.ts` regardless of the file existing or not.

## Steps to reproduce

1. create a file name `index.ts` and add any content
2. run `kube2pulumi typescript anyvalidk8s.yaml`
3. the content of `index.ts` is now lost

Expected: Doesn't overwrite `index.ts` if it exists
Actual: `kube2pulumi` overwrites `index.ts`

**Comment by stack72** [comment]
@aureq in #77, I added the ability to write the file to an output - is that sufficient to close this one out?
