### ISSUE TITLE
Parse error: Missing item separator

### ISSUE THREAD

**Issue by suhabe** [pulumi/kube2pulumi#79]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm getting the following parse error when using kube2pulumi:
```
> kube2pulumi go --file src/filebeat_autodiscover_2.1.yaml -o filebeats.go                                                                                                

Error: Error: Missing item separator

  on pcl-965641736.pp line 39:
  36: processors = [
  37: {
  38: add_cloud_metadata = null
  39: }
  40: {

Expected a comma to mark the beginning of the next item.
```

The yaml file is this one:  https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.1/config/recipes/beats/filebeat_autodiscover.yaml

### Steps to reproduce

1. Execute the command: `brew install pulumi/tap/kube2pulumi`
2. Download the yaml file at https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.1/config/recipes/beats/filebeat_autodiscover.yaml
3. Execute the command: ` kube2pulumi go --file src/filebeat_autodiscover_2.1.yaml -o filebeats.go`

Expected: kube2pulumi successfully converts the yaml file to golang
Actual: It fails and gives a parse error.

**Comment by mefuller** [comment]
I am experiencing the same issue on Ubuntu 18.04 with kube2pulumi v0.0.11:

The relevant subsection of the current YAML is:
```
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
```

And the attempt to convert the file is:
```
$ kube2pulumi go -f backstage.yaml
Error: Error: Missing item separator

  on pcl-758039703.pp line 52:
  47: envFrom = [
  48: {
  49: secretRef = {
  50: name = "postgres-secrets"
  51: },
  52: }
  53: {

Expected a comma to mark the beginning of the next item.
```
