### ISSUE TITLE
Upgrading `kube2pulumi` to use `pulumi/pulumi@3.46.0` causes changes in YAML comments

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/kube2pulumi#82]
### What happened?

Upgrading kube2pulumi to use the latest Pulumi SDK v3.46.0 forces an upgrade from [github.com/goccy/go-yaml](http://github.com/goccy/go-yaml) v1.8.*  to [github.com/goccy/go-yaml](http://github.com/goccy/go-yaml) v1.9.*. Unfortunately, go-yaml seems to have changed how comments are represented in yaml AST.

```
pkg/yaml2pcl/yaml2pcl.go:490:43: comment.Value undefined (type *ast.CommentGroupNode has no field or method Value)
pkg/yaml2pcl/yaml2pcl.go:506:11: comment.Prev undefined (type *ast.CommentGroupNode has no field or method Prev)
pkg/yaml2pcl/yaml2pcl.go:507:11: comment.Next undefined (type *ast.CommentGroupNode has no field or method Next)
```

### Steps to reproduce

see above

### Expected Behavior

no change in behavior

### Actual Behavior

change in comments

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
I dug into this, and it unfortunately appears to be a substantial breaking change in the parsing library. That got me thinking that it might be possible to swap out this conversion logic and use the library underpinning our Pulumi YAML support instead. Let's investigate that option before trying to fix these low-level changes.

**Comment by lblackstone** [comment]
After some further testing, I found that the breaking API change was in `v1.9.0` of the `go-yaml` library, so I pinned the dependency to `v1.8.10` to avoid the API change for now.
