### ISSUE TITLE
Istio gateway api error in kube2pulumi

### ISSUE THREAD

**Issue by naguait85** [pulumi/kube2pulumi#83]
### What happened?

i installed istio using pulumi helm chat using python. I am trying to convert Gateway and virtual service yaml file to python code using kube2pulumi but not able to do. Getting this error
Error: unknown resource type 'kubernetes:networking.istio.io/v1alpha3:Gateway'

### Steps to reproduce

Not working 

### Expected Behavior

Not working 

### Actual Behavior

It should work 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
That type is a CustomResource, and conversion of CRs is not currently supported by `kube2pulumi`. Closing this as a duplicate of https://github.com/pulumi/kube2pulumi/issues/53
