### ISSUE TITLE
Use Pulumi YAML support to perform the conversion

### ISSUE THREAD

**Issue by lblackstone** [pulumi/kube2pulumi#84]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
`kube2pulumi` was written before Pulumi YAML was introduced. Pulumi YAML now supports first-class conversion workflows, so it should be possible to rely on those libraries rather than maintaining a separate conversion implementation.

Related: https://github.com/pulumi/kube2pulumi/issues/82

**Comment by lblackstone** [comment]
@AaronFriel Curious if you have any thoughts about this? I think the only major difference on the conversion is that `kube2pulumi` expects k8s manifests directly, whereas Pulumi YAML would nest them under `resources` with a slightly different shape.

**Comment by AaronFriel** [comment]
I'm not sure if it makes sense to use YAML as an intermediate, except that YAML has invested in great error messages.

We've recently integrated tf2pulumi directly into the Pulumi CLI: https://github.com/pulumi/pulumi/pull/11341

If kube2pulumi exported a function to generate PCL from a directory of manifests, that seems like the natural next step. We've been naming this function `Eject` with a signature:

```go
func Eject(dir string, loader schema.ReferenceLoader) (*workspace.Project, *pcl.Program, error)
```

**Comment by lblackstone** [comment]
It sounds like this approach isn't recommended, so I'm going to close this issue. I opened #86 to track the `pulumi convert` integration story.
