### ISSUE TITLE
Integrate kube2pulumi with `pulumi convert`

### ISSUE THREAD

**Issue by lblackstone** [pulumi/kube2pulumi#86]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
See https://github.com/pulumi/kube2pulumi/issues/84#issuecomment-1316074247

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi-converter-k8s
