### ISSUE TITLE
kube2pulumi attempts to resolve literal string as variable

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/kube2pulumi#89]
### What happened?

`kube2pulumi` seems to be attempting to resolve part of a literal string as if it were a variable reference. It crashes when it can't find the obviously non-existent variable.

```
❯ kube2pulumi python -f test.yaml -o output.py
Error: Error: undefined variable datasource

  on pcl-1684386708.pp line 3:
   4: some_field = "{\\\"uid\\\": \\\"${datasource}\\\"}"


Usage:
  kube2pulumi python [flags]

Flags:
  -h, --help   help for python

Global Flags:
  -d, --directory string    file path for directory to convert
  -f, --file string         YAML file to convert
  -o, --outputFile string   The name of the output file to write to

unable to run program: Error: undefined variable datasource

  on pcl-1684386708.pp line 3:
   4: some_field = "{\\\"uid\\\": \\\"${datasource}\\\"}
```

Perhaps it is treating the literal as a format string?

### Expected Behavior

I expect it to insert the literal string exactly as it is defined in the yaml input file. It should not attempt to resolve any variables inside the literal string.

### Steps to reproduce

```yaml
apiVersion: v1
data:
  some_field: "{\"uid\": \"${datasource}\"}"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: my-app
  name: my-app-configmap
```
Put something like that in a test.yaml file, then try to run `kube2pulumi`.

```bash
kube2pulumi python -f test.yaml -o output.py
```

### Output of `pulumi about`

```
CLI          
Version      3.70.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME             VERSION
aws              5.41.0
cloudinit        1.3.0
command          0.7.2
crds             0.0.0
docker-buildkit  0.1.21
fivetran         0.1.6
frontegg         0.2.24
kubernetes       3.29.1
purrl            0.4.0
python           unknown
random           4.13.2
tls              4.10.0

Host     
OS       fedora
Version  37
Arch     x86_64

This project is written in python: executable='/home/alex/git4/cloud/venv/bin/python3' version='3.11.3
'

Current Stack: materialize/mzcloud/alexhunt

[redacted huge list of urns]
```

### Additional context

kube2pulumi version v0.0.12

This is a reduced simplified example. The actual K8S resources we're trying to convert is from rendering the Kubecost cost-analyzer Helm chart with `helm template`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alex-hunt-materialize** [comment]
The following patch seems to escape the `$`.

```patch
diff --git a/pkg/yaml2pcl/yaml2pcl.go b/pkg/yaml2pcl/yaml2pcl.go
index 5d9ba6b..1c4e314 100644
--- a/pkg/yaml2pcl/yaml2pcl.go
+++ b/pkg/yaml2pcl/yaml2pcl.go
@@ -288,6 +288,7 @@ func walkToPCL(v Visitor, node ast.Node, totalPCL io.Writer, suffix string) erro
                                        s = s[:len(s)-1]
                                }
                        }
+                       s = strings.ReplaceAll(s, "$", "$$")
                        strVal := fmt.Sprintf("%q%s", s, suffix)
                        _, err = fmt.Fprintf(totalPCL, "%s\n", strVal)
                        if err != nil {
```

**Comment by mikhailshilkov** [comment]
Thank you for reporting this @alex-hunt-materialize 

Yes, it does sound like we miss an encoding there. I don't know if it's as simple as your diff or whether it may break something currently working - would need to add tests to prove it out. Any chance you want to open a PR?

**Comment by alex-hunt-materialize** [comment]
Do you have any documentation on how to run your tests? My Go skills are... not great, and `go test ...` didn't do what I expected.

**Comment by rquitales** [comment]
> Do you have any documentation on how to run your tests? My Go skills are... not great, and `go test ...` didn't do what I expected.

Thanks for providing a diagnosis and fix for this issue @alex-hunt-materialize. I've included that in #91 which is now merged in.

For future reference, the tests can be run with `go test ./...` from the root of this repo.

**Comment by doy-materialize** [comment]
trying out version 0.0.13, i'm now seeing duplicated `$` in some places - i think the fix may have been too simplistic, and it should only have replaced `${` with `$${` instead, or something like that? i'm not familiar at all with the actual escaping rules going on here. as an example:

```
apiVersion: v1
data:
  some_field: "{\"uid\": \"$(datasource)\"}"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: my-app
  name: my-app-configmap
```

(the same as above except using `$()` instead of `${}`) produces this output:

```
import pulumi
import pulumi_kubernetes as kubernetes

my_app_configmap_config_map = kubernetes.core.v1.ConfigMap("my_app_configmapConfigMap",
    api_version="v1",
    data={
        "some_field": "{\\\"uid\\\": \\\"$$(datasource)\\\"}",
    },
    kind="ConfigMap",
    metadata=kubernetes.meta.v1.ObjectMetaArgs(
        annotations={},
        labels={
            "app": "my-app",
        },
        name="my-app-configmap",
    ))
```

which is wrong. (the previous example which used `${}` now does work and correctly result in a single `$` in the output.)

**Comment by rquitales** [comment]
Re-opening to come up with a more robust solution.

**Comment by rquitales** [comment]
v0.0.14 should address this. Digging into this, it looks like we only need to escape whenever `${` occurs as identified by @doy-materialize.
